### ISSUE TITLE
No support for altering the shell environment

### ISSUE THREAD

**Issue by jleeothon** [jleeothon/eksek#7]
In functions such as `system()` and `Open3.popen3()`, the environment is passed as an optional first argument and not as part of `opts` as we initially thought.

This means that we cannot do e.g. `eksek my_command, env: {my: variables}`.

### Solution 1

The easiest solution, and I'm fine with that, is to have the `eksek` and `Eksekutor.new` signatures as `eksek *args, opts = {}`, and just pass all the parameters to `popen3`.

However this means that we cannot as easily and directly add the `cmd` field in the `EksekResult`.

This solution also means that we can support the other ways of writing commands as supported by `popen3`, that is:

> `Open3.popen3("echo abc")`
> `Open3.popen3("echo", "abc")`
> `Open3.popen3(["echo", "argv0"], "abc")`

### Solution 2

We can also make up our own signature and decide that `env` should be a hash parameter and that we will always pass it as the first argument (or default to an empty hash) to `popen3`.

**Comment by tacconthommy** [comment]
I have to say I don't have a strong opinion on this. On one hand, I guess it could be a good thing to have a strongly structured call, on the other hand, looking at the other possible options we could provide with it, Solution 1 definitely seems the most flexible version we can come up with. AFAIR, currently we are passing the `cmd` to EksekResult` more for logging reasons in case of an error, so it wouldn't be a huuuuge issue to not have it available. And maybe there is even a way to receive it _after_ the `Open3` operation?
