### ISSUE TITLE
Implement `to_s` in `EksekResult`

### ISSUE THREAD

**Issue by jleeothon** [jleeothon/eksek#9]
Let's consider implementing `to_s` in `EksekResult`. It should return its `stdout` member, so that `eksek()` works similar to `system()` or backticks in some situations. For example:

```ruby
puts "The number of files in this directory is: #{eksek 'ls | wc -l'}"
# The number of files in this directory is: 15
```

The `inspect` method is good as it is by default.

For example:

```ruby
eksek 'ls'
#<EksekResult:0x00007fed131aafd8 @env={}, @cmd="ls", @exit_code=0, @success=true, @stdout="Gemfile\nGemfile.lock\nREADME.md\nlib\np.rb\nspec", @stderr="">
```

**Comment by tacconthommy** [comment]
What would it provide? stdout + stdin? The command? ALL of it? 🤔

**Comment by jleeothon** [comment]
`to_s` should probably be something very simple e.g. either the command or the output (maybe output is easiest because--unlike the command--it cannot be an array-or-string.

Inspect should be a much more verbose version that is helpful when debugging (it is used with the `p` method, for example).

```ruby
puts "Hello" # Hello
p "Hello" # "Hello"
puts 3 # 3
p 3 # 3
puts [1, 2, 3, 4] #1<newline>2<newline>3<newline>4
p [1, 2, 3, 4] # [1, 2, 3, 4]
```

**Comment by jleeothon** [comment]
The default implementation of `inspect` returns a string like:

```
#<EksekResult:0x00007fed131aafd8 @env={}, @cmd="ls", @exit_code=0, @success=true, @stdout="Gemfile\nGemfile.lock\nREADME.md\nlib\np.rb\nspec", @stderr="">
```

Maybe we should leave it?

**Comment by jleeothon** [comment]
@tacconthommy I updated the description of this issue to suggest a format for `EksekResult#to_s`.
